### PR TITLE
go fmt sinks_test and slack

### PR DESCRIPTION
**Pull request by samrocketman**
This kept showing up in my other pull request as an issue.  I kept discarding it in that PR but here's one to fix it for good.

I ran

```
go fmt ./...
```

### CODE REVIEW

**Review by JuHyung-Son — COMMENTED** [review]
i don't know why but fmt is different with me.
i got this after go fmt. tab size is different with you

CleanShot 2024-03-14 at 16 42 45@2x

**Comment by samrocketman** [comment]
@JuHyung-Son said:
> i don't know why but fmt is different with me. i got this after go fmt. tab size is different with you

It's not about tab size.  Your `go fmt` is indenting with 4 spaces in these files.  The rest of the project is using tab-character indenting i.e. `\t`

**Comment by samrocketman** [comment]
Another thought. Is it possible we're using different versions of go?  I'm on the latest version.  Which are you using?

**Comment by JuHyung-Son** [comment]
i use go1.21. you can see it in go.mod

im not sure it works in other version of go.


2024년 3월 16일 (토) 오전 10:39, Sam Gleske ***@***.***>님이 작성:

**Comment by samrocketman** [comment]
That's practically the same version as me go1.21.6.  Not sure what is different.

**Comment by JuHyung-Son** [comment]
yeah.. i don`t know either..
then in other files, does your fmt all changes??
in other files, formatting should look like below.

new line character start below `func`'s `c`

CleanShot 2024-03-16 at 23 02 24@2x

**Comment by samrocketman** [comment]
This PR is the result of running go fmt on all files.  The command I posted in the PR description formats everything.  It isn’t based on git diff.

**Comment by JuHyung-Son** [comment]
oh you are right. `File changed` confused me.
it should be `fmt`

**Review by AlexsJones — APPROVED** [review]

**Pull request merged**
