### PR TITLE
feat: add new RBAC configuration for k8sgpt

### LINKED ISSUE #259: [Feature]: Migrate all RBAC related resources to Helm chart's templates
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

Both manager's and k8sgpt's roles have to match in order for the former to grant permissions to K8sgpt cluster role or add the verb `escalate`. Following the Least privileged access idiom, would be great if we move away from the existing way of managing roles

### Solution Description

Lift and shift the cluster role, bindings and service account from operator's code to Helm chart's tempates

### Benefits

To be more transparent to the end users and also avoid situations like K8s API [restrictions](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#restrictions-on-role-creation-or-update) with roles which caused issues in the latest `v0.0.22`

### Potential Drawbacks

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by MateSousa**
Closes #259 

## 📑 Description
Migrate all RBAC related resources to Helm chart's templates

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by MateSousa** [comment]
@arbreezy sorry for the mess, now it's ok, and sorry for the delay, where I live we had a flu attack that made me sick.

**Review by JuHyung-Son — APPROVED** [review]
lgtm!

**Comment by arbreezy** [comment]
thanks @MateSousa
 I just need to find time to test it with existing k8sgpt-operator installations so we make sure it doesn't break anything

**Comment by AlexsJones** [comment]
> thanks @MateSousa I just need to find time to test it with existing k8sgpt-operator installations so we make sure it doesn't break anything

Let me know if you get a chance or I will later this week

**Review by arbreezy — APPROVED** [review]

**Comment by arbreezy** [comment]
DCO is not happy cause commits in this PR have been signed off with different email address.

A quick workaround is to re-open the PR and re-sign your commit(s) @MateSousa 

cc: @AlexsJones

**Pull request merged**
