### PR TITLE
feat: add mattermost sink

### LINKED ISSUE #300: [Feature]: add Mattermost Sink
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Problem Description

_No response_

### Solution Description

1. pkg/sinks
-> add mattermost.go
2. pkg/sinks/sinkreporter.go
-> add switch option ("mattermost") to NewSink method

### Benefits

Users can choose to sink into Mattermost

### Potential Drawbacks

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by tozastation**
Closes #300

## 📑 Description

1. added mattermost sink
- support mattermost incoming webhook
2. added parameter on sink (K8sGPT API)
- `Channel` (Mattermost Optional Param)
- `Username`  (Mattermost Optional Param)
- `IconURL`  (Mattermost Optional Param)
- [Mattermost Docs](https://developers.mattermost.com/integrate/webhooks/incoming/)

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

## ℹ Additional Information

1. Confirmed that no value is entered in the notification content when ai is set to `enable: false`.
(current Slack notifications may be notified with no value as well.)

Screenshot 2024-01-01 at 8 05 19 PM

Change to -> I tried to load error text when ai is enable: false.

Screenshot 2024-01-01 at 8 05 08 PM

3. E2E Test Contents
- test assets is [here](https://github.com/tozastation/k8sgpt-operator-contribute-asset/tree/main/issue-300/k8s)
  - deploy mattermost server
  - applying resources detected in k8sgpt 
  - confirmation of incoming notifications

ai.enable: false pattern

Screenshot 2024-01-01 at 8 05 08 PM

ai.enable: true pattern
Screenshot 2024-01-01 at 9 17 42 PM

### CODE REVIEW

**Comment by tozastation** [comment]
@AlexsJones 
PR created. Please review when you are available...!

**Review by AlexsJones — DISMISSED** [review]
Overall, good contribution; I was going to mention that having the channel/icon/url might be confusing to Slack sink users, but I think it's okay. 

Can I ask you please to contribute to the docs on this? 

https://github.com/k8sgpt-ai/docs ?

**Review by arbreezy — APPROVED** [review]
Lgtm !
As Alex said, let's add docs so  people know how to use it
A quick note: it's totally valid to send a report when we don't enable ai, cause message is still helpful from k8sgpt analysis. In theory we shouldn't see empty result CRs being created :thinking:

**Comment by arbreezy** [comment]
@tozastation you also have to manially uodate the helm chart crd template

**Comment by tozastation** [comment]
@AlexsJones @arbreezy 
Thanks for the review !!
I will respond to it !!

**Comment by tozastation** [comment]
@AlexsJones 

I added an explanation to README.md of k8sgpt-operator. Please check it...!
Which file should I put in k8sgpt-ai/docs?

**Review by AlexsJones — APPROVED** [review]

**Pull request merged**
