### PR TITLE
feat: rework controllers logic & add some simple tests

### PR DESCRIPTION
**Pull request by matthisholleville**
Closes # 

## 📑 Description

This PR introduces a new approach to breaking down the reconciliation loop, which has become quite complex and difficult to read. By applying this [pattern](https://refactoring.guru/design-patterns/chain-of-responsibility/go/example), we could split each step of the reconciliation loop into several distinct "steps." This would not only improve code readability but also allow us to independently test each step by mocking its inputs and outputs.

Simple integration tests have also been added, but they will need to be strengthened in the future. A testing phase should be conducted before merging this PR.

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by matthisholleville** [comment]
Tested with local mode ✅

**Review by AlexsJones — APPROVED** [review]
Looks great

**Review by JuHyung-Son — APPROVED** [review]
Impressive!
much better to maintain

**Comment by arbreezy** [comment]
Great effort @matthisholleville

**Pull request merged**
