### PR TITLE
feat: add DevSpace configuration

### PR DESCRIPTION
**Pull request by TylerGillson**
## 📑 Description
Add support for development/debugging using DevSpace.

## ✅ Checks

- [X] My pull request adheres to the code style of this project
- [X] My code requires changes to the documentation
- [X] I have updated the documentation as required
- [X] All the tests have passed

## ℹ Additional Information

image

### CODE REVIEW

**Comment by AlexsJones** [comment]
Thanks for this, personally I don't use devspace at all. @arbreezy @matthisholleville either of you?

**Comment by arbreezy** [comment]
I am not using it as well.

Said that if you feel it may help us get more contributors by making operator's development environment more familiar and easy to use for them,  maybe worth merging it

**Comment by TylerGillson** [comment]
> I am not using it as well.
> 
> Said that if you feel it may help us get more contributors by making operator's development environment more familiar and easy to use for them, maybe worth merging it

@arbreezy That's the intention! DevSpace has a pretty large and active community and IMO it speeds up k8s-native development dramatically. Being able to skip the image build/push loop is while testing changes is pretty great.

**Comment by AlexsJones** [comment]
Apologies but I don't feel like there is enough of a pull to merge this

**Pull request closed without merging**
