### PR TITLE
[Feature]: Add a field for a secret to the Sink Type

### LINKED ISSUE #309: [Feature]: Add a field for a secret to the Sink Type
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

Yes

### Problem Description

I am frustrated trying to add a sink whose endpoint contains an API Key that should remain a secret. I believe there is a security risk associated with saving endpoints that might contain secrets as plaintext strings in the CR, such as the Slack webhook URL, for example.

### Solution Description

I think the best solution would be to add a field in the Sink type for a `secret`. The creator of the sink can then determine how to use this secret to build their request in the `configure` method.

Let's consider a hypothetical Telegram bot as a sink. Requests to the Telegram API are presented in the form `https://api.telegram.org/bot<token>/METHOD_NAME`. The `https://api.telegram.org/bot` could be stored in the endpoint field, and the `token` stored as the secret. The full URL could then be assembled in the `configure` method.

### Benefits

Allows users to create sinks with secrets. Additionally, it allows users to create sinks where authentication is separate from the endpoint. For example, authentication that can be passed via headers instead of being inherently tied to the endpoint.

### Potential Drawbacks

_No response_

### Additional Information

I would be happy to work on this

### PR DESCRIPTION
**Pull request by phillipahereza**
Closes #309 

## 📑 Description
This change allows developers to configure the sink with secrets. 
Additionally, it allows developers to create sinks where the authentication is separate from the endpoint.

```yaml
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt
  namespace: gpt
spec:
  ai:
    enabled: true
    backend: noopai
  sink:
    type: telegram
    webhook: https://api.telegram.org/bot
    secret:
      name: telegram-bot-token
      key: token
```

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

## ℹ Additional Information

This PR breaks/affects #303

### CODE REVIEW

**Comment by AlexsJones** [comment]
Thanks for the contribution - does it get used anywhere yet?

**Comment by phillipahereza** [comment]
Although it's not currently in use, I believe it would be beneficial to store the Slack webhook as a secret. 

We can currently use it for Slack while maintaining backward compatibility. Check if the webhook is configured as a plaintext endpoint or a secret and utilize the appropriate one. I'm unsure whether this should be added to this PR or a separate one.

**Comment by AlexsJones** [comment]
I think if you added it into this PR it would help show the usecase @phillipahereza

**Comment by phillipahereza** [comment]
Ahhh shoot, accidentally deleted my fork 🤦. I'll open a new PR later today

**Pull request closed without merging**
